# Generated by Django 4.2.3 on 2023-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("NU", "Nubank"),
                            ("HSBC", "HSBC"),
                            ("MONZO", "Monzo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PA", "Personal Account"),
                            ("BA", "Business Account"),
                        ],
                        max_length=2,
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("bank_icon", models.ImageField(upload_to="icons")),
            ],
        ),
    ]
